### change password without credential
POST http://localhost:8085/auth/reset
Content-Type: application/json

{
  "password" : "newPassword",
  "phone_number" : "010-1234-5678",
  "token": "mock tokens"
}